name: ispectify
description: Foundation logging system for ISpect toolkit (based on Talker)
version: 4.4.0+106
homepage: https://github.com/yelmuratoff/ispect.git
issue_tracker: https://github.com/yelmuratoff/ispect/issues
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  ansicolor: ^2.0.3
  web: ^1.1.1
  collection: ^1.19.1
  meta: ^1.17.0

dev_dependencies:
  lints: ^5.1.1
